# **Naive Bayes Gaussian**

In [47]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [48]:
df=load_iris()

In [49]:
X_train, X_test, y_train, y_test = train_test_split(df.data,
                                                    df.target, test_size=0.3,
                                                    random_state=100)

In [50]:
nb=GaussianNB()
nb.fit(X_train,y_train)
predictions=nb.predict(X_test)

In [51]:
print(predictions)

[2 0 2 0 2 2 0 0 2 0 0 2 0 0 2 1 1 2 2 2 2 0 2 0 1 2 1 0 1 2 1 1 1 0 0 1 0
 1 2 2 0 1 2 2 0]


In [52]:
print("Accuraccy :",accuracy_score(y_test,predictions))

Accuraccy : 0.9555555555555556


In [53]:
print("R2 :",nb.score(X_train,y_train))

R2 : 0.9523809523809523


# **Spam** Detection with Multinomial Naive Bayes

In [54]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

# Sample dataset
emails = [
    "Win a free lottery now",
    "Hi John, how are you?",
    "Exclusive offer just for you, click now are are",
    "Let's meet for lunch tomorrow"
]
labels = [1, 0, 1, 0]  # 1 = spam, 0 = not spam

# Vectorization
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(emails)

# Split
X_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.3, random_state=42)

# Train model
model = MultinomialNB()
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

#

In [55]:
vectorizer.get_feature_names_out()

array(['are', 'click', 'exclusive', 'for', 'free', 'hi', 'how', 'john',
       'just', 'let', 'lottery', 'lunch', 'meet', 'now', 'offer',
       'tomorrow', 'win', 'you'], dtype=object)

# print the token with count in the sparse **matrix**

In [56]:
feature_names = vectorizer.get_feature_names_out()
for i, count in enumerate(X.toarray()[2]):
    if count > 0: # Only print tokens that appear in this email
        print(f"'{feature_names[i]}': {int(count)}")

'are': 2
'click': 1
'exclusive': 1
'for': 1
'just': 1
'now': 1
'offer': 1
'you': 1


In [57]:
print(X.toarray())

[[0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0]
 [1 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1]
 [2 1 1 1 0 0 0 0 1 0 0 0 0 1 1 0 0 1]
 [0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 1 0 0]]


In [58]:
X.shape[1]

18

In [59]:
print(y_pred)

[1 1]


In [60]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       2.0
           1       0.00      0.00      0.00       0.0

    accuracy                           0.00       2.0
   macro avg       0.00      0.00      0.00       2.0
weighted avg       0.00      0.00      0.00       2.0



/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_